# Development Stage
FROM node:14 AS development

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies using yarn
RUN yarn install

# Copy the rest of the application code
COPY ./ ./

# Start the development server
CMD ["yarn", "start"]
